import os
import subprocess
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def apply_auto_remediation(findings: list[dict]):
    """
    Experimental Auto-Remediation:
    Reads the high/critical findings, attempts to apply basic fixes to the files,
    creates a new branch, commits the fixes, and raises a PR using the GitHub CLI.
    """
    if not os.getenv("GITHUB_ACTIONS"):
        logger.info("Not running in GitHub Actions. Skipping auto-remediation PR creation.")
        return

    # Filter for critical/high findings
    actionable_findings = [f for f in findings if f.get("risk_score", 0) >= 6.0]
    if not actionable_findings:
        logger.info("No actionable high/critical findings for auto-remediation.")
        return

    branch_name = f"xaisec-auto-fix-{int(datetime.now().timestamp())}"
    
    try:
        # 1. Create a new branch
        subprocess.run(["git", "checkout", "-b", branch_name], check=True)
        
        # 2. Apply fixes (Prototype: appending fix comments above the vulnerable line)
        # In a full implementation, this would use AST or LLM to precisely replace the vulnerable code.
        files_modified = set()
        for finding in actionable_findings:
            file_path = finding["file"]
            line_num = finding["line_start"]
            rule_id = finding["rule_id"]
            rec = finding.get("recommendation", {})
            fix_text = rec.get("fix", "Review this line for vulnerabilities.")
            
            if not os.path.exists(file_path):
                continue
                
            with open(file_path, "r") as f:
                lines = f.readlines()
                
            # Insert the fix comment right above the vulnerable line
            # Format it nicely as a multi-line comment
            fix_comment = f"    # [XAI-SecOps Auto-Remediation Suggestion for {rule_id}]\n"
            for f_line in fix_text.split('\n'):
                fix_comment += f"    # {f_line}\n"
                
            # 0-indexed line_num
            insert_idx = max(0, line_num - 1)
            lines.insert(insert_idx, fix_comment)
            
            with open(file_path, "w") as f:
                f.writelines(lines)
            files_modified.add(file_path)

        if not files_modified:
            logger.info("No files were successfully modified.")
            return

        # 3. Commit the changes
        subprocess.run(["git", "config", "--global", "user.name", "github-actions[bot]"], check=True)
        subprocess.run(["git", "config", "--global", "user.email", "github-actions[bot]@users.noreply.github.com"], check=True)
        subprocess.run(["git", "add", "."], check=True)
        subprocess.run(["git", "commit", "-m", "🔒 Auto-Remediation: Apply XAI-SecOps security fixes"], check=True)
        
        # 4. Push the branch
        subprocess.run(["git", "push", "origin", branch_name], check=True)
        
        # 5. Create the PR using GitHub CLI (gh)
        pr_title = "🔒 Auto-Remediation: Security Fixes from XAI-SecOps"
        pr_body = (
            "## 🛡️ XAI-SecOps Auto-Remediation\n\n"
            "This PR was automatically generated by the XAI-SecOps bot to fix critical vulnerabilities "
            "detected in the latest scan.\n\n"
            "**Please review the changes carefully before merging. These fixes were generated by an AI agent and require human verification.**\n\n"
            "### Vulnerabilities Addressed:\n"
        )
        for finding in actionable_findings:
            pr_body += f"- **{finding['rule_id']}** in `{finding['file']}:{finding['line_start']}`\n"
            
        subprocess.run([
            "gh", "pr", "create",
            "--title", pr_title,
            "--body", pr_body,
            "--head", branch_name,
            "--base", "main"
        ], check=True, env={**os.environ, "GH_TOKEN": os.environ.get("GITHUB_TOKEN")})
        
        logger.info(f"Successfully created Auto-Remediation PR from branch {branch_name}")

    except subprocess.CalledProcessError as e:
        logger.error(f"Auto-Remediation failed during git/gh operations: {e}")
